# Generated by Django 5.0.4 on 2024-04-27 14:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_type_forum_description_forum_file_forum_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 14, 50, 46, 504412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 14, 50, 46, 504412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topics',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 14, 50, 46, 504412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TopicComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 14, 50, 46, 504412, tzinfo=datetime.timezone.utc))),
                ('commentors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.forum')),
            ],
        ),
    ]
