# Generated by Django 5.0.4 on 2024-04-27 23:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_comments_comment_date_alter_forum_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 23, 28, 30, 382095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 23, 28, 30, 382095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 23, 28, 30, 382095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topiccomments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 23, 28, 30, 382095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topics',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 23, 28, 30, 382095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('file', models.FileField(upload_to='media/announcement', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'pdf', 'word', 'ppt', 'xlsx', 'csv', 'gif'])])),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 23, 28, 30, 382095, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField()),
                ('like', models.IntegerField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
