# Generated by Django 5.0.4 on 2024-04-28 00:30

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_announcement_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='like',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 0, 30, 7, 192222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 0, 30, 7, 192222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 0, 30, 7, 192222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 0, 30, 7, 192222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topiccomments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 0, 30, 7, 192222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topics',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 0, 30, 7, 192222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='announcement',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
