# Generated by Django 5.0.4 on 2024-05-08 22:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_announcement_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='title',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 22, 33, 24, 32899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 22, 33, 24, 32899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 22, 33, 24, 32899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 22, 33, 24, 32899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 22, 33, 24, 32899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topiccomments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 22, 33, 24, 32899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topics',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/topics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'pdf', 'mp3', 'mp4word', 'ppt', 'xlsx', 'csv', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='topics',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 22, 33, 24, 32899, tzinfo=datetime.timezone.utc)),
        ),
    ]
