# Generated by Django 5.0.4 on 2024-05-09 01:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_announcement_title_remove_events_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topiccomments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topics',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/webinar', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2024, 5, 9, 1, 24, 18, 670962, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
